### ISSUE TITLE
[SUGGESTION] Is there a way for invincible monsters to have HP?

### ISSUE THREAD

**Issue by parakatins** [nyakowint/EverythingGoBoom-LC#12]
I think your mod is brilliant, however I use a mod that adds several landmines, on the outside too, (SuperLandmines).
and it's really sad to see a jester die to a random landmine on the ground.
If there is any way to configure how many explosions each monster can take (jester 5, giants 3, for example)
With this you can even use LethalThings' rocket launcher to kill these invincible monsters

this would be incredible, like two people with rocket lunchers trying to kill a jester, but with him fighting back

Well, I don't know anything about programming at all and how difficult it would be to program this, 😅

**Comment by nyakowint** [comment]
Technically vanilla "invincible" monsters  (jester for ex.) already have 3 HP by default, this would probably just be a matter of increasing that HP. So doable and will consider just broading the scope of the mod in this case so enemy HP is configurable, perhaps

**Comment by parakatins** [comment]
> Technically vanilla "invincible" monsters (jester for ex.) already have 3 HP by default, this would probably just be a matter of increasing that HP. So doable and will consider just broading the scope of the mod in this case so enemy HP is configurable, perhaps


thank you very much for your attention ❤️, happy new year!!

**Comment by GoldenKittenPlays** [comment]
> > Technically vanilla "invincible" monsters (jester for ex.) already have 3 HP by default, this would probably just be a matter of increasing that HP. So doable and will consider just broading the scope of the mod in this case so enemy HP is configurable, perhaps
> 
> thank you very much for your attention ❤️, happy new year!!

I think I was able to implement it but lemme know otherwise
