### ISSUE TITLE
[Suggestion] Please add a blanket config to make all things killable without making them explosive

### ISSUE THREAD

**Issue by SpazzMaticus107** [nyakowint/EverythingGoBoom-LC#15]
I was hoping I could make the giants and some other stuff killable but it the config it says that it to make things killable I would have to make them "boomable" at the same time. Can we have an extra option to make all enemies killable without them exploding?

**Comment by GoldenKittenPlays** [comment]
> I was hoping I could make the giants and some other stuff killable but it the config it says that it to make things killable I would have to make them "boomable" at the same time. Can we have an extra option to make all enemies killable without them exploding?

ALready a config option called explodeable
