### ISSUE TITLE
Immortal enemies are still immortal

### ISSUE THREAD

**Issue by quirkyquokka1999** [nyakowint/EverythingGoBoom-LC#18]
Hi I have been changing the configuration so immortal enemies can die but not explode and the enemies that are normally not killable are still not killable despite being set up to do so. I shot a puffer with a shotgun like ten times and nothing happened. Is there something in the settings wrong because I have all normally immortal enemies set to be shootable, hittable, and rocketable. Also I see health is configurable but I cannot find anywhere to edit this in the configuration file?

**Comment by nyakowint** [comment]
Shotguns/rockets may still be a little weird in functionality i'll have to check with golden on that one

**Comment by quirkyquokka1999** [comment]
Thank you! Are shovels then working? I haven't tried that yet

**Comment by nyakowint** [comment]
Shovels *should* work as thats what I originally modded before I handed over control, ymmv

**Comment by quirkyquokka1999** [comment]
Thanks so much and I will give shovels ago. Let me know if you find out anything about the shotguns :)

**Comment by nyakowint** [comment]
Maybe related to #21, let me know if this still happens I'll have to actually go look at it (v50 made this mod even harder to test, the utility mods i used are broken lol)

**Comment by Entity378** [comment]
The problem has definitely been solved with version 1.2.17 .
