### ISSUE TITLE
[Bug] Config won't generate correctly with LC_Office installed

### ISSUE THREAD

**Issue by JohnMetroid** [nyakowint/EverythingGoBoom-LC#27]
when booting up modded lethal, the config appears to be created improperly because of enemies associated with LC_Office.  Specifically, "Halt" does not have any health, I believe.  So when trying to import that value, your routine breaks and no further config information is populated

**Comment by Entity378** [comment]
I have it fixed but I still need to fix one more issue with the rad mech before releasing the update

**Comment by JohnMetroid** [comment]
Thank you for the fix, the config seems to be generating fine now.

A bunch of the enemy health values are incorrect, though.  For instance: Tulip Snakes have 3 hp in your config, but have 1 hp in vanilla.  Vanilla hoarding bug is 2 hp, but config is 3 hp.  Vanilla centipede is 2 hp, but config is 3 hp.

I also thought that radmech hp was missing as well, but the config appears to be generating this entry separate from the other radmech config options.

**Comment by Entity378** [comment]
> Thank you for the fix, the config seems to be generating fine now.
> 
> A bunch of the enemy health values are incorrect, though. For instance: Tulip Snakes have 3 hp in your config, but have 1 hp in vanilla. Vanilla hoarding bug is 2 hp, but config is 3 hp. Vanilla centipede is 2 hp, but config is 3 hp.
> 
> I also thought that radmech hp was missing as well, but the config appears to be generating this entry separate from the other radmech config options.

some entities take double or even 5 times the damage they should receive, the HP values ​​are those that are dictated by the game and not by me. I can't fix the problem of entities taking more instances of damage than they should, it's not a problem with the mod but with the vanilla game.

**Comment by Entity378** [comment]
Also I don't have the slightest idea why the RadMech config is generated multiple times, probably the vanilla game or another mod creates a different instance of the RadMech when the game starts. Regardless, I recommend regenerating the configs

**Comment by JohnMetroid** [comment]
Howdy, I checked again after regenerating the config, and RadMech is still being generated incorrectly.  No mods for Rad Mech

```
[06:18:58.6141388] [Error  :EverythingCanDie] It was not possible to generate the configs for the enemy: RadMech
```

**Comment by Entity378** [comment]
I don't know what to say since it generates the config correctly for me.

**Comment by JohnMetroid** [comment]
thank you for double checking

if I can find out more information about the source of the conflict I'll be sure to update you
