### ISSUE TITLE
(Suggestion) Expose hexibettershotgun's cfgs?

### ISSUE THREAD

**Issue by crumplaude** [nyakowint/EverythingGoBoom-LC#31]
I had both this and HexiBetterShotgunFixed by Entity378 installed at the same time before realizing it caused a conflict with the shotgun eating both shells in 1 shot, but upon disabling Hexi's I notice that this mod doesn't have the pellet count and angle cfg options that the original did, which I had made use of to make the shotgun more powerful for this exact sort of mod.

**Comment by Entity378** [comment]
I suggest using my version of HexiBetterShotgun anyway if you want to change configs. I'll probably remove the HexiBetterShotgun part from EverythingCanDie altogether at some point.
