### ISSUE TITLE
mobs who were invincible sometimes won't die.

### ISSUE THREAD

**Issue by EisiaDEV** [nyakowint/EverythingGoBoom-LC#35]
There must be something wrong with it, because in some cases it dies, and in some cases it doesn't.

**Comment by XionDEV-214** [comment]
ok plus, exactly coilhead in mansion cannot be killed(randomly).

0191561a-4563-ab6e-b9f5-027b27ef1610 mod profile.

**Comment by Entity378** [comment]
from the tests I have done I can say that the mod works correctly. I need the logs to understand what could be the problem you are having.
